port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "rizkikotet"
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - msftconnecttest.com
      - msftncsi.com
      - "+.*"
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    - 1.0.0.1
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 185.228.168.9
    - 185.228.169.168
    - 76.76.2.0
    - 76.76.10.0
    - 94.140.14.140
    - 94.140.14.141
    - 172.105.216.54
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
proxy-groups:
  - name: SERVER-BROWSING
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use:
      - PP-Browsing
    url: http://www.gstatic.com/generate_204
    interval: "360"
  - name: SERVER-ID
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use:
      - PP-Indo
    url: http://www.gstatic.com/generate_204
    interval: "360"
  - name: Traffic-Direct
    type: select
    disable-udp: false
    proxies:
      - DIRECT-ISP1
      - DIRECT-ISP2
      - DIRECT-LB
    use:
      - PP-Game
      - PP-Indo
      - PP-Browsing
  - name: Traffic-Gaming
    type: select
    disable-udp: false
    proxies:
      - DIRECT-ISP1
      - DIRECT-ISP2
      - DIRECT-LB
    use:
      - PP-Game
      - PP-Indo
      - PP-Browsing
  - name: Traffic-Gaming-Port
    type: select
    disable-udp: false
    proxies:
      - DIRECT-ISP1
      - DIRECT-ISP2
      - DIRECT-LB
    use:
      - PP-Game
      - PP-Indo
      - PP-Browsing
  - name: Traffic-Indo
    type: fallback
    disable-udp: false
    proxies:
      - SERVER-ID
      - SERVER-BROWSING
    url: http://www.gstatic.com/generate_204
    interval: "30"
  - name: Traffic-Browsing
    type: fallback
    disable-udp: false
    proxies:
      - SERVER-BROWSING
      - SERVER-ID
    url: http://www.gstatic.com/generate_204
    interval: "30"
  - name: Traffic-Manual-Reject
    type: select
    disable-udp: false
    proxies:
      - REJECT
      - Traffic-Browsing
      - Traffic-Indo
  - name: Traffic-Porn
    type: select
    disable-udp: false
    proxies:
      - REJECT
      - Traffic-Browsing
      - Traffic-Indo
  - name: Traffic-Ads
    type: select
    disable-udp: false
    proxies:
      - REJECT
      - Traffic-Browsing
      - Traffic-Indo
  - name: DIRECT-LB
    type: load-balance
    strategy: round-robin
    disable-udp: false
    proxies:
      - DIRECT-ISP1
      - DIRECT-ISP2
    url: http://www.gstatic.com/generate_204
    interval: "360"
  - name: DIRECT-ISP1
    interface-name: eth1
    type: select
    disable-udp: false
    proxies:
      - DIRECT
  - name: DIRECT-ISP2
    interface-name: eth2
    type: select
    disable-udp: false
    proxies:
      - DIRECT
proxy-providers:
  PP-Indo:
    type: file
    path: "./proxy_provider/pp-indo.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  PP-Browsing:
    type: file
    path: "./proxy_provider/pp-browsing.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  PP-Game:
    type: file
    path: "./proxy_provider/pp-gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
rule-providers:
  RP-Direct:
    type: file
    behavior: classical
    path: "./rule_provider/rp-direct.yaml"
  RP-Umum:
    type: file
    behavior: classical
    path: "./rule_provider/rp-umum.yaml"
  RP-Reject:
    type: file
    behavior: classical
    path: "./rule_provider/rp-reject.yaml"
  RP-Indo:
    type: file
    behavior: classical
    path: "./rule_provider/rp-indo.yaml"
rules:
  - DST-PORT,123/136/137-139,Traffic-Direct,udp
  - RULE-SET,RP-Direct,Traffic-Direct #MANUAL DIRECT
  - RULE-SET,RP-Reject,Traffic-Manual-Reject #MANUAL REJECT / BLOCK
  - AND,((NETWORK,udp),(OR,((DST-PORT,443),(GEOSITE,youtube)))),REJECT #QUIC
  # ======= ADS BOKEP =======
  - AND,((GEOSITE,oisd-full),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),Traffic-Ads #ADS
  - AND,((GEOSITE,rule-ads),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),Traffic-Ads #ADS
  - GEOSITE,oisd-nsfw,Traffic-Porn #PORN BOKEP
  # ======= ADS BOKEP =======

  # ======= KELUARGA GOOGLE =======
  - GEOIP,GOOGLE,Traffic-Browsing
  - GEOSITE,GOOGLE,Traffic-Browsing
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),Traffic-Browsing
  - AND,((NETWORK,UDP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),Traffic-Browsing
  # ======= KELUARGA GOOGLE =======

  # ======= ALL TRAFIK INDO =======
  - GEOSITE,rule-indo,Traffic-Indo
  - GEOSITE,rule-sosmed,Traffic-Indo
  - GEOSITE,rule-streaming,Traffic-Indo
  - GEOIP,id,Traffic-Indo
  - GEOIP,facebook,Traffic-Indo
  - GEOIP,netflix,Traffic-Indo
  - GEOIP,telegram,Traffic-Indo
  - GEOIP,twitter,Traffic-Indo
  - RULE-SET,RP-Indo,Traffic-Indo # Manual Indo
  # ======= ALL TRAFIK INDO =======

  # ======= GAME =======
  - GEOSITE,rule-gaming,Traffic-Gaming
  - AND,((NOT,((RULE-SET,RP-Umum))),(NETWORK,TCP)),Traffic-Gaming-Port
  - AND,((NOT,((RULE-SET,RP-Umum))),(NETWORK,UDP)),Traffic-Gaming-Port
  # ======= GAME =======

  - GEOSITE,rule-speedtest,Traffic-Browsing
  - AND,((RULE-SET,RP-Umum),(NETWORK,TCP)),Traffic-Browsing
  - AND,((RULE-SET,RP-Umum),(NETWORK,UDP)),Traffic-Browsing
  - MATCH,Traffic-Browsing
