on:
  workflow_dispatch:
  push:
    branches:
      - master

name: Create Release


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Move and zip files
      run: |
        mkdir -p ./publish/
        wget https://raw.githubusercontent.com/xishang0128/geoip/release/Country.mmdb -O ./publish/country-lite.mmdb
        wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb -O ./publish/country.mmdb

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './publish/'
        destination_repo: 'rtaserver/Config-Open-ClashMeta'
        destination_folder: 'config'
        user_email: 'example@email.com'
        user_name: 'dmnemec'
        commit_message: 'Released on ${{ env.BUILDTIME }}'
