# release action with semantic release
name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  reporta: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "BUILDTIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        shell: bash

      - name: Set timezone to WIB Jakarta
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Indonesia Standard Time"

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r="## :mega:Update content"
          r="${r//$'\n'/'![](https://img.shields.io/github/downloads/${{ env.reporta }}/${{needs.job_check.outputs.reporta_version}}/total?style=flat-square)'}"
          r="${r//$'\n'/'### GeoSite - GeoDat Info'}"
          r="${r//$'\n'/'### Created By : RizkiKotet'}"
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Released RTA-SERVER on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
